"""empty message

Revision ID: 5f6bb947ff0b
Revises: 1ca5cd61fa7a
Create Date: 2024-12-23 03:07:33.765112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6bb947ff0b'
down_revision = '1ca5cd61fa7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_column('pet_count')

    # ### end Alembic commands ###
